version: '3.7'
services:
  node:
    build: .
    ports:
      - "8080:3000"
    depends_on:
      - mongodb_container
    environment:
      DB_HOST: mongodb_container
      DB_DATABASE: express_sockets
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
